# Generated by Django 5.0.6 on 2026-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "SEO Setting",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="in_featured_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="in_top_list",
            field=models.BooleanField(default=False),
        ),
    ]
