# Generated by Django 5.0.6 on 2026-05-17 17:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="short_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
