# Generated by Django 5.0.6 on 2026-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_description_alter_job_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="short_description",
        ),
        migrations.AddField(
            model_name="joblink",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="joblink",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
