# Generated by Django 5.0.6 on 2026-05-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_seosetting_job_in_featured_list_job_in_top_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="posted_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
