# Generated by Django 5.0.6 on 2026-05-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_job_posted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="jobs/featured-images/"
            ),
        ),
    ]
