# Generated by Django 5.0.6 on 2026-05-27 02:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_remove_job_short_description_joblink_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFaqs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("faqs", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_faqs",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job FAQ",
                "verbose_name_plural": "Job FAQs",
            },
        ),
    ]
