# Generated by Django 5.0.6 on 2026-05-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_jobfaqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
