# Generated by Django 5.0.6 on 2026-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="notification_msg",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
