# Generated by Django 5.0.6 on 2026-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_question_quiztitle_option_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiztitle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
