# Generated by Django 5.0.6 on 2026-05-31 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_quiztitle_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_desc",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
