# Generated by Django 5.0.6 on 2026-05-31 13:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_question_question_desc_alter_question_question_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="quiztitle",
            name="quiz_desc",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="jobs.tag"
            ),
        ),
        migrations.AddField(
            model_name="quiztitle",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="quizzes", to="jobs.tag"
            ),
        ),
    ]
