# Generated by Django 5.0.6 on 2026-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_tag_quiztitle_quiz_desc_job_tags_quiztitle_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiztitle",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
