# Generated by Django 5.0.6 on 2026-06-08 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_quiztitle_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblink",
            old_name="is_primary",
            new_name="is_new",
        ),
    ]
