# Generated by Django 5.0.6 on 2026-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_rename_is_primary_joblink_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=400, unique=True),
        ),
    ]
