# Generated by Django 5.0.6 on 2026-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_alter_job_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="category",
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="jobs.category"
            ),
        ),
    ]
