# Generated by Django 5.0.6 on 2026-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_remove_job_category_job_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblink",
            name="url",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
